name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'portfolio-spa/package-lock.json'

      - name: Install dependencies
        working-directory: ./portfolio-spa
        run: npm install

      - name: Build
        working-directory: ./portfolio-spa
        run: npm run build -- --base-href "/"

      - name: Create CNAME file
        run: echo "yeisoncardona.com" > ./portfolio-spa/dist/YeisonCardona/browser/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./portfolio-spa/dist/YeisonCardona/browser
          branch: gh-pages
          clean: true